/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vital.api.resources.team.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.vital.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonDeserialize(builder = TeamUpdateSourcePrioritiesRequest.Builder.class)
public final class TeamUpdateSourcePrioritiesRequest {
    private final String teamId;

    private final Map<String, Object> additionalProperties;

    private TeamUpdateSourcePrioritiesRequest(String teamId, Map<String, Object> additionalProperties) {
        this.teamId = teamId;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("team_id")
    public String getTeamId() {
        return teamId;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof TeamUpdateSourcePrioritiesRequest && equalTo((TeamUpdateSourcePrioritiesRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(TeamUpdateSourcePrioritiesRequest other) {
        return teamId.equals(other.teamId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.teamId);
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static TeamIdStage builder() {
        return new Builder();
    }

    public interface TeamIdStage {
        _FinalStage teamId(String teamId);

        Builder from(TeamUpdateSourcePrioritiesRequest other);
    }

    public interface _FinalStage {
        TeamUpdateSourcePrioritiesRequest build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements TeamIdStage, _FinalStage {
        private String teamId;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @Override
        public Builder from(TeamUpdateSourcePrioritiesRequest other) {
            teamId(other.getTeamId());
            return this;
        }

        @Override
        @JsonSetter("team_id")
        public _FinalStage teamId(String teamId) {
            this.teamId = teamId;
            return this;
        }

        @Override
        public TeamUpdateSourcePrioritiesRequest build() {
            return new TeamUpdateSourcePrioritiesRequest(teamId, additionalProperties);
        }
    }
}
