/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vital.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.vital.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = AppointmentBookingRequest.Builder.class)
public final class AppointmentBookingRequest {
    private final String bookingKey;

    private final Map<String, Object> additionalProperties;

    private AppointmentBookingRequest(String bookingKey, Map<String, Object> additionalProperties) {
        this.bookingKey = bookingKey;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("booking_key")
    public String getBookingKey() {
        return bookingKey;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof AppointmentBookingRequest && equalTo((AppointmentBookingRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(AppointmentBookingRequest other) {
        return bookingKey.equals(other.bookingKey);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.bookingKey);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static BookingKeyStage builder() {
        return new Builder();
    }

    public interface BookingKeyStage {
        _FinalStage bookingKey(@NotNull String bookingKey);

        Builder from(AppointmentBookingRequest other);
    }

    public interface _FinalStage {
        AppointmentBookingRequest build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements BookingKeyStage, _FinalStage {
        private String bookingKey;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(AppointmentBookingRequest other) {
            bookingKey(other.getBookingKey());
            return this;
        }

        @java.lang.Override
        @JsonSetter("booking_key")
        public _FinalStage bookingKey(@NotNull String bookingKey) {
            this.bookingKey = Objects.requireNonNull(bookingKey, "bookingKey must not be null");
            return this;
        }

        @java.lang.Override
        public AppointmentBookingRequest build() {
            return new AppointmentBookingRequest(bookingKey, additionalProperties);
        }
    }
}
