/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vital.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.vital.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = AppointmentBookingRequest.Builder.class)
public final class AppointmentBookingRequest {
    private final String bookingKey;

    private final Optional<Boolean> asyncConfirmation;

    private final Optional<Integer> syncConfirmationTimeoutMillisecond;

    private final Optional<Integer> asyncConfirmationTimeoutMillisecond;

    private final Map<String, Object> additionalProperties;

    private AppointmentBookingRequest(
            String bookingKey,
            Optional<Boolean> asyncConfirmation,
            Optional<Integer> syncConfirmationTimeoutMillisecond,
            Optional<Integer> asyncConfirmationTimeoutMillisecond,
            Map<String, Object> additionalProperties) {
        this.bookingKey = bookingKey;
        this.asyncConfirmation = asyncConfirmation;
        this.syncConfirmationTimeoutMillisecond = syncConfirmationTimeoutMillisecond;
        this.asyncConfirmationTimeoutMillisecond = asyncConfirmationTimeoutMillisecond;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("booking_key")
    public String getBookingKey() {
        return bookingKey;
    }

    /**
     * @return If true, the endpoint attempts to confirm the booking within the <code>sync_confirmation_timeout_millisecond</code> window. If confirmation is not received in time, a pending appointment is returned and booking continues asynchronously. If false (default), the endpoint waits for confirmation or returns a 500 error on failure.
     */
    @JsonProperty("async_confirmation")
    public Optional<Boolean> getAsyncConfirmation() {
        return asyncConfirmation;
    }

    /**
     * @return Maximum time (in milliseconds) to wait for booking confirmation before returning a pending appointment. Only applies when <code>async_confirmation</code> is true. Defaults to 2500ms. Range: 1000-10000ms.
     */
    @JsonProperty("sync_confirmation_timeout_millisecond")
    public Optional<Integer> getSyncConfirmationTimeoutMillisecond() {
        return syncConfirmationTimeoutMillisecond;
    }

    /**
     * @return Maximum time (in milliseconds) to attempt asynchronous booking before cancelling the pending appointment. Only applies when <code>async_confirmation</code> is true. Defaults to 15 minutes. Range: 60000-172800000ms.
     */
    @JsonProperty("async_confirmation_timeout_millisecond")
    public Optional<Integer> getAsyncConfirmationTimeoutMillisecond() {
        return asyncConfirmationTimeoutMillisecond;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof AppointmentBookingRequest && equalTo((AppointmentBookingRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(AppointmentBookingRequest other) {
        return bookingKey.equals(other.bookingKey)
                && asyncConfirmation.equals(other.asyncConfirmation)
                && syncConfirmationTimeoutMillisecond.equals(other.syncConfirmationTimeoutMillisecond)
                && asyncConfirmationTimeoutMillisecond.equals(other.asyncConfirmationTimeoutMillisecond);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.bookingKey,
                this.asyncConfirmation,
                this.syncConfirmationTimeoutMillisecond,
                this.asyncConfirmationTimeoutMillisecond);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static BookingKeyStage builder() {
        return new Builder();
    }

    public interface BookingKeyStage {
        _FinalStage bookingKey(@NotNull String bookingKey);

        Builder from(AppointmentBookingRequest other);
    }

    public interface _FinalStage {
        AppointmentBookingRequest build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>If true, the endpoint attempts to confirm the booking within the <code>sync_confirmation_timeout_millisecond</code> window. If confirmation is not received in time, a pending appointment is returned and booking continues asynchronously. If false (default), the endpoint waits for confirmation or returns a 500 error on failure.</p>
         */
        _FinalStage asyncConfirmation(Optional<Boolean> asyncConfirmation);

        _FinalStage asyncConfirmation(Boolean asyncConfirmation);

        /**
         * <p>Maximum time (in milliseconds) to wait for booking confirmation before returning a pending appointment. Only applies when <code>async_confirmation</code> is true. Defaults to 2500ms. Range: 1000-10000ms.</p>
         */
        _FinalStage syncConfirmationTimeoutMillisecond(Optional<Integer> syncConfirmationTimeoutMillisecond);

        _FinalStage syncConfirmationTimeoutMillisecond(Integer syncConfirmationTimeoutMillisecond);

        /**
         * <p>Maximum time (in milliseconds) to attempt asynchronous booking before cancelling the pending appointment. Only applies when <code>async_confirmation</code> is true. Defaults to 15 minutes. Range: 60000-172800000ms.</p>
         */
        _FinalStage asyncConfirmationTimeoutMillisecond(Optional<Integer> asyncConfirmationTimeoutMillisecond);

        _FinalStage asyncConfirmationTimeoutMillisecond(Integer asyncConfirmationTimeoutMillisecond);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements BookingKeyStage, _FinalStage {
        private String bookingKey;

        private Optional<Integer> asyncConfirmationTimeoutMillisecond = Optional.empty();

        private Optional<Integer> syncConfirmationTimeoutMillisecond = Optional.empty();

        private Optional<Boolean> asyncConfirmation = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(AppointmentBookingRequest other) {
            bookingKey(other.getBookingKey());
            asyncConfirmation(other.getAsyncConfirmation());
            syncConfirmationTimeoutMillisecond(other.getSyncConfirmationTimeoutMillisecond());
            asyncConfirmationTimeoutMillisecond(other.getAsyncConfirmationTimeoutMillisecond());
            return this;
        }

        @java.lang.Override
        @JsonSetter("booking_key")
        public _FinalStage bookingKey(@NotNull String bookingKey) {
            this.bookingKey = Objects.requireNonNull(bookingKey, "bookingKey must not be null");
            return this;
        }

        /**
         * <p>Maximum time (in milliseconds) to attempt asynchronous booking before cancelling the pending appointment. Only applies when <code>async_confirmation</code> is true. Defaults to 15 minutes. Range: 60000-172800000ms.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage asyncConfirmationTimeoutMillisecond(Integer asyncConfirmationTimeoutMillisecond) {
            this.asyncConfirmationTimeoutMillisecond = Optional.ofNullable(asyncConfirmationTimeoutMillisecond);
            return this;
        }

        /**
         * <p>Maximum time (in milliseconds) to attempt asynchronous booking before cancelling the pending appointment. Only applies when <code>async_confirmation</code> is true. Defaults to 15 minutes. Range: 60000-172800000ms.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "async_confirmation_timeout_millisecond", nulls = Nulls.SKIP)
        public _FinalStage asyncConfirmationTimeoutMillisecond(Optional<Integer> asyncConfirmationTimeoutMillisecond) {
            this.asyncConfirmationTimeoutMillisecond = asyncConfirmationTimeoutMillisecond;
            return this;
        }

        /**
         * <p>Maximum time (in milliseconds) to wait for booking confirmation before returning a pending appointment. Only applies when <code>async_confirmation</code> is true. Defaults to 2500ms. Range: 1000-10000ms.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage syncConfirmationTimeoutMillisecond(Integer syncConfirmationTimeoutMillisecond) {
            this.syncConfirmationTimeoutMillisecond = Optional.ofNullable(syncConfirmationTimeoutMillisecond);
            return this;
        }

        /**
         * <p>Maximum time (in milliseconds) to wait for booking confirmation before returning a pending appointment. Only applies when <code>async_confirmation</code> is true. Defaults to 2500ms. Range: 1000-10000ms.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "sync_confirmation_timeout_millisecond", nulls = Nulls.SKIP)
        public _FinalStage syncConfirmationTimeoutMillisecond(Optional<Integer> syncConfirmationTimeoutMillisecond) {
            this.syncConfirmationTimeoutMillisecond = syncConfirmationTimeoutMillisecond;
            return this;
        }

        /**
         * <p>If true, the endpoint attempts to confirm the booking within the <code>sync_confirmation_timeout_millisecond</code> window. If confirmation is not received in time, a pending appointment is returned and booking continues asynchronously. If false (default), the endpoint waits for confirmation or returns a 500 error on failure.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage asyncConfirmation(Boolean asyncConfirmation) {
            this.asyncConfirmation = Optional.ofNullable(asyncConfirmation);
            return this;
        }

        /**
         * <p>If true, the endpoint attempts to confirm the booking within the <code>sync_confirmation_timeout_millisecond</code> window. If confirmation is not received in time, a pending appointment is returned and booking continues asynchronously. If false (default), the endpoint waits for confirmation or returns a 500 error on failure.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "async_confirmation", nulls = Nulls.SKIP)
        public _FinalStage asyncConfirmation(Optional<Boolean> asyncConfirmation) {
            this.asyncConfirmation = asyncConfirmation;
            return this;
        }

        @java.lang.Override
        public AppointmentBookingRequest build() {
            return new AppointmentBookingRequest(
                    bookingKey,
                    asyncConfirmation,
                    syncConfirmationTimeoutMillisecond,
                    asyncConfirmationTimeoutMillisecond,
                    additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
