/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vital.api.types;

import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.vital.api.core.ObjectMappers;
import java.io.IOException;
import java.util.List;
import java.util.Objects;
import java.util.Optional;

@JsonDeserialize(using = ClientFacingStreamResistance.Deserializer.class)
public final class ClientFacingStreamResistance {
    private final Object value;

    private final int type;

    private ClientFacingStreamResistance(Object value, int type) {
        this.value = value;
        this.type = type;
    }

    @JsonValue
    public Object get() {
        return this.value;
    }

    @SuppressWarnings("unchecked")
    public <T> T visit(Visitor<T> visitor) {
        if (this.type == 0) {
            return visitor.visitListOfOptionalDouble((List<Optional<Double>>) this.value);
        } else if (this.type == 1) {
            return visitor.visitListOfDouble((List<Double>) this.value);
        }
        throw new IllegalStateException("Failed to visit value. This should never happen.");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ClientFacingStreamResistance && equalTo((ClientFacingStreamResistance) other);
    }

    private boolean equalTo(ClientFacingStreamResistance other) {
        return value.equals(other.value);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.value);
    }

    @java.lang.Override
    public String toString() {
        return this.value.toString();
    }

    public static ClientFacingStreamResistance ofListOfOptionalDouble(List<Optional<Double>> value) {
        return new ClientFacingStreamResistance(value, 0);
    }

    public static ClientFacingStreamResistance ofListOfDouble(List<Double> value) {
        return new ClientFacingStreamResistance(value, 1);
    }

    public interface Visitor<T> {
        T visitListOfOptionalDouble(List<Optional<Double>> value);

        T visitListOfDouble(List<Double> value);
    }

    static final class Deserializer extends StdDeserializer<ClientFacingStreamResistance> {
        Deserializer() {
            super(ClientFacingStreamResistance.class);
        }

        @java.lang.Override
        public ClientFacingStreamResistance deserialize(JsonParser p, DeserializationContext context)
                throws IOException {
            Object value = p.readValueAs(Object.class);
            try {
                return ofListOfOptionalDouble(
                        ObjectMappers.JSON_MAPPER.convertValue(value, new TypeReference<List<Optional<Double>>>() {}));
            } catch (RuntimeException e) {
            }
            try {
                return ofListOfDouble(
                        ObjectMappers.JSON_MAPPER.convertValue(value, new TypeReference<List<Double>>() {}));
            } catch (RuntimeException e) {
            }
            throw new JsonParseException(p, "Failed to deserialize");
        }
    }
}
