/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vital.api.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum ClientFacingWorkoutDurationChangedEventType {
    DAILY_DATA_WORKOUT_DURATION_CREATED("daily.data.workout_duration.created"),

    DAILY_DATA_WORKOUT_DURATION_UPDATED("daily.data.workout_duration.updated");

    private final String value;

    ClientFacingWorkoutDurationChangedEventType(String value) {
        this.value = value;
    }

    @JsonValue
    @java.lang.Override
    public String toString() {
        return this.value;
    }
}
