/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vital.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.vital.api.core.Nullable;
import com.vital.api.core.NullableNonemptyFilter;
import com.vital.api.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ClientFacingWorkout.Builder.class)
public final class ClientFacingWorkout {
    private final String id;

    private final String userId;

    private final Optional<String> title;

    private final Optional<Integer> timezoneOffset;

    private final Optional<Integer> averageHr;

    private final Optional<Integer> maxHr;

    private final Optional<Double> distance;

    private final String calendarDate;

    private final OffsetDateTime timeStart;

    private final OffsetDateTime timeEnd;

    private final Optional<Double> calories;

    private final Optional<ClientFacingSport> sport;

    private final Optional<List<Integer>> hrZones;

    private final Optional<Integer> movingTime;

    private final Optional<Double> totalElevationGain;

    private final Optional<Double> elevHigh;

    private final Optional<Double> elevLow;

    private final Optional<Double> averageSpeed;

    private final Optional<Double> maxSpeed;

    private final Optional<Double> averageWatts;

    private final Optional<Double> deviceWatts;

    private final Optional<Double> maxWatts;

    private final Optional<Double> weightedAverageWatts;

    private final Optional<Integer> steps;

    private final Optional<ClientFacingWorkoutMap> map;

    private final String providerId;

    private final ClientFacingSource source;

    private final OffsetDateTime createdAt;

    private final OffsetDateTime updatedAt;

    private final Map<String, Object> additionalProperties;

    private ClientFacingWorkout(
            String id,
            String userId,
            Optional<String> title,
            Optional<Integer> timezoneOffset,
            Optional<Integer> averageHr,
            Optional<Integer> maxHr,
            Optional<Double> distance,
            String calendarDate,
            OffsetDateTime timeStart,
            OffsetDateTime timeEnd,
            Optional<Double> calories,
            Optional<ClientFacingSport> sport,
            Optional<List<Integer>> hrZones,
            Optional<Integer> movingTime,
            Optional<Double> totalElevationGain,
            Optional<Double> elevHigh,
            Optional<Double> elevLow,
            Optional<Double> averageSpeed,
            Optional<Double> maxSpeed,
            Optional<Double> averageWatts,
            Optional<Double> deviceWatts,
            Optional<Double> maxWatts,
            Optional<Double> weightedAverageWatts,
            Optional<Integer> steps,
            Optional<ClientFacingWorkoutMap> map,
            String providerId,
            ClientFacingSource source,
            OffsetDateTime createdAt,
            OffsetDateTime updatedAt,
            Map<String, Object> additionalProperties) {
        this.id = id;
        this.userId = userId;
        this.title = title;
        this.timezoneOffset = timezoneOffset;
        this.averageHr = averageHr;
        this.maxHr = maxHr;
        this.distance = distance;
        this.calendarDate = calendarDate;
        this.timeStart = timeStart;
        this.timeEnd = timeEnd;
        this.calories = calories;
        this.sport = sport;
        this.hrZones = hrZones;
        this.movingTime = movingTime;
        this.totalElevationGain = totalElevationGain;
        this.elevHigh = elevHigh;
        this.elevLow = elevLow;
        this.averageSpeed = averageSpeed;
        this.maxSpeed = maxSpeed;
        this.averageWatts = averageWatts;
        this.deviceWatts = deviceWatts;
        this.maxWatts = maxWatts;
        this.weightedAverageWatts = weightedAverageWatts;
        this.steps = steps;
        this.map = map;
        this.providerId = providerId;
        this.source = source;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("id")
    public String getId() {
        return id;
    }

    /**
     * @return User id returned by vital create user request. This id should be stored in your database against the user and used for all interactions with the vital api.
     */
    @JsonProperty("user_id")
    public String getUserId() {
        return userId;
    }

    /**
     * @return Title given for the workout
     */
    @JsonIgnore
    public Optional<String> getTitle() {
        if (title == null) {
            return Optional.empty();
        }
        return title;
    }

    /**
     * @return Timezone offset from UTC as seconds. For example, EEST (Eastern European Summer Time, +3h) is 10800. PST (Pacific Standard Time, -8h) is -28800::seconds
     */
    @JsonIgnore
    public Optional<Integer> getTimezoneOffset() {
        if (timezoneOffset == null) {
            return Optional.empty();
        }
        return timezoneOffset;
    }

    /**
     * @return Average heart rate during workout::bpm
     */
    @JsonIgnore
    public Optional<Integer> getAverageHr() {
        if (averageHr == null) {
            return Optional.empty();
        }
        return averageHr;
    }

    /**
     * @return Max heart rate during workout::bpm
     */
    @JsonIgnore
    public Optional<Integer> getMaxHr() {
        if (maxHr == null) {
            return Optional.empty();
        }
        return maxHr;
    }

    /**
     * @return Distance travelled during workout::meters
     */
    @JsonIgnore
    public Optional<Double> getDistance() {
        if (distance == null) {
            return Optional.empty();
        }
        return distance;
    }

    /**
     * @return Date of the workout summary in the YYYY-mm-dd format. This generally matches the workout start date.
     */
    @JsonProperty("calendar_date")
    public String getCalendarDate() {
        return calendarDate;
    }

    /**
     * @return Start time of the workout::time
     */
    @JsonProperty("time_start")
    public OffsetDateTime getTimeStart() {
        return timeStart;
    }

    /**
     * @return End time of the workout::time
     */
    @JsonProperty("time_end")
    public OffsetDateTime getTimeEnd() {
        return timeEnd;
    }

    /**
     * @return Calories burned during the workout::kCal
     */
    @JsonIgnore
    public Optional<Double> getCalories() {
        if (calories == null) {
            return Optional.empty();
        }
        return calories;
    }

    /**
     * @return Sport's name
     */
    @JsonProperty("sport")
    public Optional<ClientFacingSport> getSport() {
        return sport;
    }

    /**
     * @return Time in seconds spent in different heart rate zones &lt;50%, 50-60%, 60-70%, 70-80%, 80-90%, 90%+. Due to rounding errors, it's possible that summing all values is different than the total time of the workout. Not available for all providers::seconds
     */
    @JsonIgnore
    public Optional<List<Integer>> getHrZones() {
        if (hrZones == null) {
            return Optional.empty();
        }
        return hrZones;
    }

    /**
     * @return Time spent active during the workout::seconds
     */
    @JsonIgnore
    public Optional<Integer> getMovingTime() {
        if (movingTime == null) {
            return Optional.empty();
        }
        return movingTime;
    }

    /**
     * @return Elevation gain during the workout::meters
     */
    @JsonIgnore
    public Optional<Double> getTotalElevationGain() {
        if (totalElevationGain == null) {
            return Optional.empty();
        }
        return totalElevationGain;
    }

    /**
     * @return Highest point of elevation::meters
     */
    @JsonIgnore
    public Optional<Double> getElevHigh() {
        if (elevHigh == null) {
            return Optional.empty();
        }
        return elevHigh;
    }

    /**
     * @return Lowest point of elevation::meters
     */
    @JsonIgnore
    public Optional<Double> getElevLow() {
        if (elevLow == null) {
            return Optional.empty();
        }
        return elevLow;
    }

    /**
     * @return Average speed during workout in m/s::meters/sec
     */
    @JsonIgnore
    public Optional<Double> getAverageSpeed() {
        if (averageSpeed == null) {
            return Optional.empty();
        }
        return averageSpeed;
    }

    /**
     * @return Max speed during workout in m/s::meters/sec
     */
    @JsonIgnore
    public Optional<Double> getMaxSpeed() {
        if (maxSpeed == null) {
            return Optional.empty();
        }
        return maxSpeed;
    }

    /**
     * @return Average watts burned during exercise::watts
     */
    @JsonIgnore
    public Optional<Double> getAverageWatts() {
        if (averageWatts == null) {
            return Optional.empty();
        }
        return averageWatts;
    }

    /**
     * @return Watts burned during exercise::watts
     */
    @JsonIgnore
    public Optional<Double> getDeviceWatts() {
        if (deviceWatts == null) {
            return Optional.empty();
        }
        return deviceWatts;
    }

    /**
     * @return Max watts burned during exercise::watts
     */
    @JsonIgnore
    public Optional<Double> getMaxWatts() {
        if (maxWatts == null) {
            return Optional.empty();
        }
        return maxWatts;
    }

    /**
     * @return Weighted average watts burned during exercise::watts
     */
    @JsonIgnore
    public Optional<Double> getWeightedAverageWatts() {
        if (weightedAverageWatts == null) {
            return Optional.empty();
        }
        return weightedAverageWatts;
    }

    /**
     * @return Number of steps accumulated during this workout::count
     */
    @JsonIgnore
    public Optional<Integer> getSteps() {
        if (steps == null) {
            return Optional.empty();
        }
        return steps;
    }

    /**
     * @return Map of the workout
     */
    @JsonIgnore
    public Optional<ClientFacingWorkoutMap> getMap() {
        if (map == null) {
            return Optional.empty();
        }
        return map;
    }

    /**
     * @return Provider ID given for that specific workout
     */
    @JsonProperty("provider_id")
    public String getProviderId() {
        return providerId;
    }

    /**
     * @return Source the data has come from.
     */
    @JsonProperty("source")
    public ClientFacingSource getSource() {
        return source;
    }

    @JsonProperty("created_at")
    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    @JsonProperty("updated_at")
    public OffsetDateTime getUpdatedAt() {
        return updatedAt;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("title")
    private Optional<String> _getTitle() {
        return title;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("timezone_offset")
    private Optional<Integer> _getTimezoneOffset() {
        return timezoneOffset;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("average_hr")
    private Optional<Integer> _getAverageHr() {
        return averageHr;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("max_hr")
    private Optional<Integer> _getMaxHr() {
        return maxHr;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("distance")
    private Optional<Double> _getDistance() {
        return distance;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("calories")
    private Optional<Double> _getCalories() {
        return calories;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("hr_zones")
    private Optional<List<Integer>> _getHrZones() {
        return hrZones;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("moving_time")
    private Optional<Integer> _getMovingTime() {
        return movingTime;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("total_elevation_gain")
    private Optional<Double> _getTotalElevationGain() {
        return totalElevationGain;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("elev_high")
    private Optional<Double> _getElevHigh() {
        return elevHigh;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("elev_low")
    private Optional<Double> _getElevLow() {
        return elevLow;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("average_speed")
    private Optional<Double> _getAverageSpeed() {
        return averageSpeed;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("max_speed")
    private Optional<Double> _getMaxSpeed() {
        return maxSpeed;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("average_watts")
    private Optional<Double> _getAverageWatts() {
        return averageWatts;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("device_watts")
    private Optional<Double> _getDeviceWatts() {
        return deviceWatts;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("max_watts")
    private Optional<Double> _getMaxWatts() {
        return maxWatts;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("weighted_average_watts")
    private Optional<Double> _getWeightedAverageWatts() {
        return weightedAverageWatts;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("steps")
    private Optional<Integer> _getSteps() {
        return steps;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("map")
    private Optional<ClientFacingWorkoutMap> _getMap() {
        return map;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ClientFacingWorkout && equalTo((ClientFacingWorkout) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ClientFacingWorkout other) {
        return id.equals(other.id)
                && userId.equals(other.userId)
                && title.equals(other.title)
                && timezoneOffset.equals(other.timezoneOffset)
                && averageHr.equals(other.averageHr)
                && maxHr.equals(other.maxHr)
                && distance.equals(other.distance)
                && calendarDate.equals(other.calendarDate)
                && timeStart.equals(other.timeStart)
                && timeEnd.equals(other.timeEnd)
                && calories.equals(other.calories)
                && sport.equals(other.sport)
                && hrZones.equals(other.hrZones)
                && movingTime.equals(other.movingTime)
                && totalElevationGain.equals(other.totalElevationGain)
                && elevHigh.equals(other.elevHigh)
                && elevLow.equals(other.elevLow)
                && averageSpeed.equals(other.averageSpeed)
                && maxSpeed.equals(other.maxSpeed)
                && averageWatts.equals(other.averageWatts)
                && deviceWatts.equals(other.deviceWatts)
                && maxWatts.equals(other.maxWatts)
                && weightedAverageWatts.equals(other.weightedAverageWatts)
                && steps.equals(other.steps)
                && map.equals(other.map)
                && providerId.equals(other.providerId)
                && source.equals(other.source)
                && createdAt.equals(other.createdAt)
                && updatedAt.equals(other.updatedAt);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.id,
                this.userId,
                this.title,
                this.timezoneOffset,
                this.averageHr,
                this.maxHr,
                this.distance,
                this.calendarDate,
                this.timeStart,
                this.timeEnd,
                this.calories,
                this.sport,
                this.hrZones,
                this.movingTime,
                this.totalElevationGain,
                this.elevHigh,
                this.elevLow,
                this.averageSpeed,
                this.maxSpeed,
                this.averageWatts,
                this.deviceWatts,
                this.maxWatts,
                this.weightedAverageWatts,
                this.steps,
                this.map,
                this.providerId,
                this.source,
                this.createdAt,
                this.updatedAt);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IdStage builder() {
        return new Builder();
    }

    public interface IdStage {
        UserIdStage id(@NotNull String id);

        Builder from(ClientFacingWorkout other);
    }

    public interface UserIdStage {
        /**
         * <p>User id returned by vital create user request. This id should be stored in your database against the user and used for all interactions with the vital api.</p>
         */
        CalendarDateStage userId(@NotNull String userId);
    }

    public interface CalendarDateStage {
        /**
         * <p>Date of the workout summary in the YYYY-mm-dd format. This generally matches the workout start date.</p>
         */
        TimeStartStage calendarDate(@NotNull String calendarDate);
    }

    public interface TimeStartStage {
        /**
         * <p>Start time of the workout::time</p>
         */
        TimeEndStage timeStart(@NotNull OffsetDateTime timeStart);
    }

    public interface TimeEndStage {
        /**
         * <p>End time of the workout::time</p>
         */
        ProviderIdStage timeEnd(@NotNull OffsetDateTime timeEnd);
    }

    public interface ProviderIdStage {
        /**
         * <p>Provider ID given for that specific workout</p>
         */
        SourceStage providerId(@NotNull String providerId);
    }

    public interface SourceStage {
        /**
         * <p>Source the data has come from.</p>
         */
        CreatedAtStage source(@NotNull ClientFacingSource source);
    }

    public interface CreatedAtStage {
        UpdatedAtStage createdAt(@NotNull OffsetDateTime createdAt);
    }

    public interface UpdatedAtStage {
        _FinalStage updatedAt(@NotNull OffsetDateTime updatedAt);
    }

    public interface _FinalStage {
        ClientFacingWorkout build();

        /**
         * <p>Title given for the workout</p>
         */
        _FinalStage title(Optional<String> title);

        _FinalStage title(String title);

        _FinalStage title(Nullable<String> title);

        /**
         * <p>Timezone offset from UTC as seconds. For example, EEST (Eastern European Summer Time, +3h) is 10800. PST (Pacific Standard Time, -8h) is -28800::seconds</p>
         */
        _FinalStage timezoneOffset(Optional<Integer> timezoneOffset);

        _FinalStage timezoneOffset(Integer timezoneOffset);

        _FinalStage timezoneOffset(Nullable<Integer> timezoneOffset);

        /**
         * <p>Average heart rate during workout::bpm</p>
         */
        _FinalStage averageHr(Optional<Integer> averageHr);

        _FinalStage averageHr(Integer averageHr);

        _FinalStage averageHr(Nullable<Integer> averageHr);

        /**
         * <p>Max heart rate during workout::bpm</p>
         */
        _FinalStage maxHr(Optional<Integer> maxHr);

        _FinalStage maxHr(Integer maxHr);

        _FinalStage maxHr(Nullable<Integer> maxHr);

        /**
         * <p>Distance travelled during workout::meters</p>
         */
        _FinalStage distance(Optional<Double> distance);

        _FinalStage distance(Double distance);

        _FinalStage distance(Nullable<Double> distance);

        /**
         * <p>Calories burned during the workout::kCal</p>
         */
        _FinalStage calories(Optional<Double> calories);

        _FinalStage calories(Double calories);

        _FinalStage calories(Nullable<Double> calories);

        /**
         * <p>Sport's name</p>
         */
        _FinalStage sport(Optional<ClientFacingSport> sport);

        _FinalStage sport(ClientFacingSport sport);

        /**
         * <p>Time in seconds spent in different heart rate zones &lt;50%, 50-60%, 60-70%, 70-80%, 80-90%, 90%+. Due to rounding errors, it's possible that summing all values is different than the total time of the workout. Not available for all providers::seconds</p>
         */
        _FinalStage hrZones(Optional<List<Integer>> hrZones);

        _FinalStage hrZones(List<Integer> hrZones);

        _FinalStage hrZones(Nullable<List<Integer>> hrZones);

        /**
         * <p>Time spent active during the workout::seconds</p>
         */
        _FinalStage movingTime(Optional<Integer> movingTime);

        _FinalStage movingTime(Integer movingTime);

        _FinalStage movingTime(Nullable<Integer> movingTime);

        /**
         * <p>Elevation gain during the workout::meters</p>
         */
        _FinalStage totalElevationGain(Optional<Double> totalElevationGain);

        _FinalStage totalElevationGain(Double totalElevationGain);

        _FinalStage totalElevationGain(Nullable<Double> totalElevationGain);

        /**
         * <p>Highest point of elevation::meters</p>
         */
        _FinalStage elevHigh(Optional<Double> elevHigh);

        _FinalStage elevHigh(Double elevHigh);

        _FinalStage elevHigh(Nullable<Double> elevHigh);

        /**
         * <p>Lowest point of elevation::meters</p>
         */
        _FinalStage elevLow(Optional<Double> elevLow);

        _FinalStage elevLow(Double elevLow);

        _FinalStage elevLow(Nullable<Double> elevLow);

        /**
         * <p>Average speed during workout in m/s::meters/sec</p>
         */
        _FinalStage averageSpeed(Optional<Double> averageSpeed);

        _FinalStage averageSpeed(Double averageSpeed);

        _FinalStage averageSpeed(Nullable<Double> averageSpeed);

        /**
         * <p>Max speed during workout in m/s::meters/sec</p>
         */
        _FinalStage maxSpeed(Optional<Double> maxSpeed);

        _FinalStage maxSpeed(Double maxSpeed);

        _FinalStage maxSpeed(Nullable<Double> maxSpeed);

        /**
         * <p>Average watts burned during exercise::watts</p>
         */
        _FinalStage averageWatts(Optional<Double> averageWatts);

        _FinalStage averageWatts(Double averageWatts);

        _FinalStage averageWatts(Nullable<Double> averageWatts);

        /**
         * <p>Watts burned during exercise::watts</p>
         */
        _FinalStage deviceWatts(Optional<Double> deviceWatts);

        _FinalStage deviceWatts(Double deviceWatts);

        _FinalStage deviceWatts(Nullable<Double> deviceWatts);

        /**
         * <p>Max watts burned during exercise::watts</p>
         */
        _FinalStage maxWatts(Optional<Double> maxWatts);

        _FinalStage maxWatts(Double maxWatts);

        _FinalStage maxWatts(Nullable<Double> maxWatts);

        /**
         * <p>Weighted average watts burned during exercise::watts</p>
         */
        _FinalStage weightedAverageWatts(Optional<Double> weightedAverageWatts);

        _FinalStage weightedAverageWatts(Double weightedAverageWatts);

        _FinalStage weightedAverageWatts(Nullable<Double> weightedAverageWatts);

        /**
         * <p>Number of steps accumulated during this workout::count</p>
         */
        _FinalStage steps(Optional<Integer> steps);

        _FinalStage steps(Integer steps);

        _FinalStage steps(Nullable<Integer> steps);

        /**
         * <p>Map of the workout</p>
         */
        _FinalStage map(Optional<ClientFacingWorkoutMap> map);

        _FinalStage map(ClientFacingWorkoutMap map);

        _FinalStage map(Nullable<ClientFacingWorkoutMap> map);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements IdStage,
                    UserIdStage,
                    CalendarDateStage,
                    TimeStartStage,
                    TimeEndStage,
                    ProviderIdStage,
                    SourceStage,
                    CreatedAtStage,
                    UpdatedAtStage,
                    _FinalStage {
        private String id;

        private String userId;

        private String calendarDate;

        private OffsetDateTime timeStart;

        private OffsetDateTime timeEnd;

        private String providerId;

        private ClientFacingSource source;

        private OffsetDateTime createdAt;

        private OffsetDateTime updatedAt;

        private Optional<ClientFacingWorkoutMap> map = Optional.empty();

        private Optional<Integer> steps = Optional.empty();

        private Optional<Double> weightedAverageWatts = Optional.empty();

        private Optional<Double> maxWatts = Optional.empty();

        private Optional<Double> deviceWatts = Optional.empty();

        private Optional<Double> averageWatts = Optional.empty();

        private Optional<Double> maxSpeed = Optional.empty();

        private Optional<Double> averageSpeed = Optional.empty();

        private Optional<Double> elevLow = Optional.empty();

        private Optional<Double> elevHigh = Optional.empty();

        private Optional<Double> totalElevationGain = Optional.empty();

        private Optional<Integer> movingTime = Optional.empty();

        private Optional<List<Integer>> hrZones = Optional.empty();

        private Optional<ClientFacingSport> sport = Optional.empty();

        private Optional<Double> calories = Optional.empty();

        private Optional<Double> distance = Optional.empty();

        private Optional<Integer> maxHr = Optional.empty();

        private Optional<Integer> averageHr = Optional.empty();

        private Optional<Integer> timezoneOffset = Optional.empty();

        private Optional<String> title = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ClientFacingWorkout other) {
            id(other.getId());
            userId(other.getUserId());
            title(other.getTitle());
            timezoneOffset(other.getTimezoneOffset());
            averageHr(other.getAverageHr());
            maxHr(other.getMaxHr());
            distance(other.getDistance());
            calendarDate(other.getCalendarDate());
            timeStart(other.getTimeStart());
            timeEnd(other.getTimeEnd());
            calories(other.getCalories());
            sport(other.getSport());
            hrZones(other.getHrZones());
            movingTime(other.getMovingTime());
            totalElevationGain(other.getTotalElevationGain());
            elevHigh(other.getElevHigh());
            elevLow(other.getElevLow());
            averageSpeed(other.getAverageSpeed());
            maxSpeed(other.getMaxSpeed());
            averageWatts(other.getAverageWatts());
            deviceWatts(other.getDeviceWatts());
            maxWatts(other.getMaxWatts());
            weightedAverageWatts(other.getWeightedAverageWatts());
            steps(other.getSteps());
            map(other.getMap());
            providerId(other.getProviderId());
            source(other.getSource());
            createdAt(other.getCreatedAt());
            updatedAt(other.getUpdatedAt());
            return this;
        }

        @java.lang.Override
        @JsonSetter("id")
        public UserIdStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        /**
         * <p>User id returned by vital create user request. This id should be stored in your database against the user and used for all interactions with the vital api.</p>
         * <p>User id returned by vital create user request. This id should be stored in your database against the user and used for all interactions with the vital api.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("user_id")
        public CalendarDateStage userId(@NotNull String userId) {
            this.userId = Objects.requireNonNull(userId, "userId must not be null");
            return this;
        }

        /**
         * <p>Date of the workout summary in the YYYY-mm-dd format. This generally matches the workout start date.</p>
         * <p>Date of the workout summary in the YYYY-mm-dd format. This generally matches the workout start date.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("calendar_date")
        public TimeStartStage calendarDate(@NotNull String calendarDate) {
            this.calendarDate = Objects.requireNonNull(calendarDate, "calendarDate must not be null");
            return this;
        }

        /**
         * <p>Start time of the workout::time</p>
         * <p>Start time of the workout::time</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("time_start")
        public TimeEndStage timeStart(@NotNull OffsetDateTime timeStart) {
            this.timeStart = Objects.requireNonNull(timeStart, "timeStart must not be null");
            return this;
        }

        /**
         * <p>End time of the workout::time</p>
         * <p>End time of the workout::time</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("time_end")
        public ProviderIdStage timeEnd(@NotNull OffsetDateTime timeEnd) {
            this.timeEnd = Objects.requireNonNull(timeEnd, "timeEnd must not be null");
            return this;
        }

        /**
         * <p>Provider ID given for that specific workout</p>
         * <p>Provider ID given for that specific workout</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("provider_id")
        public SourceStage providerId(@NotNull String providerId) {
            this.providerId = Objects.requireNonNull(providerId, "providerId must not be null");
            return this;
        }

        /**
         * <p>Source the data has come from.</p>
         * <p>Source the data has come from.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("source")
        public CreatedAtStage source(@NotNull ClientFacingSource source) {
            this.source = Objects.requireNonNull(source, "source must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("created_at")
        public UpdatedAtStage createdAt(@NotNull OffsetDateTime createdAt) {
            this.createdAt = Objects.requireNonNull(createdAt, "createdAt must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("updated_at")
        public _FinalStage updatedAt(@NotNull OffsetDateTime updatedAt) {
            this.updatedAt = Objects.requireNonNull(updatedAt, "updatedAt must not be null");
            return this;
        }

        /**
         * <p>Map of the workout</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage map(Nullable<ClientFacingWorkoutMap> map) {
            if (map.isNull()) {
                this.map = null;
            } else if (map.isEmpty()) {
                this.map = Optional.empty();
            } else {
                this.map = Optional.of(map.get());
            }
            return this;
        }

        /**
         * <p>Map of the workout</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage map(ClientFacingWorkoutMap map) {
            this.map = Optional.ofNullable(map);
            return this;
        }

        /**
         * <p>Map of the workout</p>
         */
        @java.lang.Override
        @JsonSetter(value = "map", nulls = Nulls.SKIP)
        public _FinalStage map(Optional<ClientFacingWorkoutMap> map) {
            this.map = map;
            return this;
        }

        /**
         * <p>Number of steps accumulated during this workout::count</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage steps(Nullable<Integer> steps) {
            if (steps.isNull()) {
                this.steps = null;
            } else if (steps.isEmpty()) {
                this.steps = Optional.empty();
            } else {
                this.steps = Optional.of(steps.get());
            }
            return this;
        }

        /**
         * <p>Number of steps accumulated during this workout::count</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage steps(Integer steps) {
            this.steps = Optional.ofNullable(steps);
            return this;
        }

        /**
         * <p>Number of steps accumulated during this workout::count</p>
         */
        @java.lang.Override
        @JsonSetter(value = "steps", nulls = Nulls.SKIP)
        public _FinalStage steps(Optional<Integer> steps) {
            this.steps = steps;
            return this;
        }

        /**
         * <p>Weighted average watts burned during exercise::watts</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage weightedAverageWatts(Nullable<Double> weightedAverageWatts) {
            if (weightedAverageWatts.isNull()) {
                this.weightedAverageWatts = null;
            } else if (weightedAverageWatts.isEmpty()) {
                this.weightedAverageWatts = Optional.empty();
            } else {
                this.weightedAverageWatts = Optional.of(weightedAverageWatts.get());
            }
            return this;
        }

        /**
         * <p>Weighted average watts burned during exercise::watts</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage weightedAverageWatts(Double weightedAverageWatts) {
            this.weightedAverageWatts = Optional.ofNullable(weightedAverageWatts);
            return this;
        }

        /**
         * <p>Weighted average watts burned during exercise::watts</p>
         */
        @java.lang.Override
        @JsonSetter(value = "weighted_average_watts", nulls = Nulls.SKIP)
        public _FinalStage weightedAverageWatts(Optional<Double> weightedAverageWatts) {
            this.weightedAverageWatts = weightedAverageWatts;
            return this;
        }

        /**
         * <p>Max watts burned during exercise::watts</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage maxWatts(Nullable<Double> maxWatts) {
            if (maxWatts.isNull()) {
                this.maxWatts = null;
            } else if (maxWatts.isEmpty()) {
                this.maxWatts = Optional.empty();
            } else {
                this.maxWatts = Optional.of(maxWatts.get());
            }
            return this;
        }

        /**
         * <p>Max watts burned during exercise::watts</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage maxWatts(Double maxWatts) {
            this.maxWatts = Optional.ofNullable(maxWatts);
            return this;
        }

        /**
         * <p>Max watts burned during exercise::watts</p>
         */
        @java.lang.Override
        @JsonSetter(value = "max_watts", nulls = Nulls.SKIP)
        public _FinalStage maxWatts(Optional<Double> maxWatts) {
            this.maxWatts = maxWatts;
            return this;
        }

        /**
         * <p>Watts burned during exercise::watts</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage deviceWatts(Nullable<Double> deviceWatts) {
            if (deviceWatts.isNull()) {
                this.deviceWatts = null;
            } else if (deviceWatts.isEmpty()) {
                this.deviceWatts = Optional.empty();
            } else {
                this.deviceWatts = Optional.of(deviceWatts.get());
            }
            return this;
        }

        /**
         * <p>Watts burned during exercise::watts</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage deviceWatts(Double deviceWatts) {
            this.deviceWatts = Optional.ofNullable(deviceWatts);
            return this;
        }

        /**
         * <p>Watts burned during exercise::watts</p>
         */
        @java.lang.Override
        @JsonSetter(value = "device_watts", nulls = Nulls.SKIP)
        public _FinalStage deviceWatts(Optional<Double> deviceWatts) {
            this.deviceWatts = deviceWatts;
            return this;
        }

        /**
         * <p>Average watts burned during exercise::watts</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage averageWatts(Nullable<Double> averageWatts) {
            if (averageWatts.isNull()) {
                this.averageWatts = null;
            } else if (averageWatts.isEmpty()) {
                this.averageWatts = Optional.empty();
            } else {
                this.averageWatts = Optional.of(averageWatts.get());
            }
            return this;
        }

        /**
         * <p>Average watts burned during exercise::watts</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage averageWatts(Double averageWatts) {
            this.averageWatts = Optional.ofNullable(averageWatts);
            return this;
        }

        /**
         * <p>Average watts burned during exercise::watts</p>
         */
        @java.lang.Override
        @JsonSetter(value = "average_watts", nulls = Nulls.SKIP)
        public _FinalStage averageWatts(Optional<Double> averageWatts) {
            this.averageWatts = averageWatts;
            return this;
        }

        /**
         * <p>Max speed during workout in m/s::meters/sec</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage maxSpeed(Nullable<Double> maxSpeed) {
            if (maxSpeed.isNull()) {
                this.maxSpeed = null;
            } else if (maxSpeed.isEmpty()) {
                this.maxSpeed = Optional.empty();
            } else {
                this.maxSpeed = Optional.of(maxSpeed.get());
            }
            return this;
        }

        /**
         * <p>Max speed during workout in m/s::meters/sec</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage maxSpeed(Double maxSpeed) {
            this.maxSpeed = Optional.ofNullable(maxSpeed);
            return this;
        }

        /**
         * <p>Max speed during workout in m/s::meters/sec</p>
         */
        @java.lang.Override
        @JsonSetter(value = "max_speed", nulls = Nulls.SKIP)
        public _FinalStage maxSpeed(Optional<Double> maxSpeed) {
            this.maxSpeed = maxSpeed;
            return this;
        }

        /**
         * <p>Average speed during workout in m/s::meters/sec</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage averageSpeed(Nullable<Double> averageSpeed) {
            if (averageSpeed.isNull()) {
                this.averageSpeed = null;
            } else if (averageSpeed.isEmpty()) {
                this.averageSpeed = Optional.empty();
            } else {
                this.averageSpeed = Optional.of(averageSpeed.get());
            }
            return this;
        }

        /**
         * <p>Average speed during workout in m/s::meters/sec</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage averageSpeed(Double averageSpeed) {
            this.averageSpeed = Optional.ofNullable(averageSpeed);
            return this;
        }

        /**
         * <p>Average speed during workout in m/s::meters/sec</p>
         */
        @java.lang.Override
        @JsonSetter(value = "average_speed", nulls = Nulls.SKIP)
        public _FinalStage averageSpeed(Optional<Double> averageSpeed) {
            this.averageSpeed = averageSpeed;
            return this;
        }

        /**
         * <p>Lowest point of elevation::meters</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage elevLow(Nullable<Double> elevLow) {
            if (elevLow.isNull()) {
                this.elevLow = null;
            } else if (elevLow.isEmpty()) {
                this.elevLow = Optional.empty();
            } else {
                this.elevLow = Optional.of(elevLow.get());
            }
            return this;
        }

        /**
         * <p>Lowest point of elevation::meters</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage elevLow(Double elevLow) {
            this.elevLow = Optional.ofNullable(elevLow);
            return this;
        }

        /**
         * <p>Lowest point of elevation::meters</p>
         */
        @java.lang.Override
        @JsonSetter(value = "elev_low", nulls = Nulls.SKIP)
        public _FinalStage elevLow(Optional<Double> elevLow) {
            this.elevLow = elevLow;
            return this;
        }

        /**
         * <p>Highest point of elevation::meters</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage elevHigh(Nullable<Double> elevHigh) {
            if (elevHigh.isNull()) {
                this.elevHigh = null;
            } else if (elevHigh.isEmpty()) {
                this.elevHigh = Optional.empty();
            } else {
                this.elevHigh = Optional.of(elevHigh.get());
            }
            return this;
        }

        /**
         * <p>Highest point of elevation::meters</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage elevHigh(Double elevHigh) {
            this.elevHigh = Optional.ofNullable(elevHigh);
            return this;
        }

        /**
         * <p>Highest point of elevation::meters</p>
         */
        @java.lang.Override
        @JsonSetter(value = "elev_high", nulls = Nulls.SKIP)
        public _FinalStage elevHigh(Optional<Double> elevHigh) {
            this.elevHigh = elevHigh;
            return this;
        }

        /**
         * <p>Elevation gain during the workout::meters</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage totalElevationGain(Nullable<Double> totalElevationGain) {
            if (totalElevationGain.isNull()) {
                this.totalElevationGain = null;
            } else if (totalElevationGain.isEmpty()) {
                this.totalElevationGain = Optional.empty();
            } else {
                this.totalElevationGain = Optional.of(totalElevationGain.get());
            }
            return this;
        }

        /**
         * <p>Elevation gain during the workout::meters</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage totalElevationGain(Double totalElevationGain) {
            this.totalElevationGain = Optional.ofNullable(totalElevationGain);
            return this;
        }

        /**
         * <p>Elevation gain during the workout::meters</p>
         */
        @java.lang.Override
        @JsonSetter(value = "total_elevation_gain", nulls = Nulls.SKIP)
        public _FinalStage totalElevationGain(Optional<Double> totalElevationGain) {
            this.totalElevationGain = totalElevationGain;
            return this;
        }

        /**
         * <p>Time spent active during the workout::seconds</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage movingTime(Nullable<Integer> movingTime) {
            if (movingTime.isNull()) {
                this.movingTime = null;
            } else if (movingTime.isEmpty()) {
                this.movingTime = Optional.empty();
            } else {
                this.movingTime = Optional.of(movingTime.get());
            }
            return this;
        }

        /**
         * <p>Time spent active during the workout::seconds</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage movingTime(Integer movingTime) {
            this.movingTime = Optional.ofNullable(movingTime);
            return this;
        }

        /**
         * <p>Time spent active during the workout::seconds</p>
         */
        @java.lang.Override
        @JsonSetter(value = "moving_time", nulls = Nulls.SKIP)
        public _FinalStage movingTime(Optional<Integer> movingTime) {
            this.movingTime = movingTime;
            return this;
        }

        /**
         * <p>Time in seconds spent in different heart rate zones &lt;50%, 50-60%, 60-70%, 70-80%, 80-90%, 90%+. Due to rounding errors, it's possible that summing all values is different than the total time of the workout. Not available for all providers::seconds</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage hrZones(Nullable<List<Integer>> hrZones) {
            if (hrZones.isNull()) {
                this.hrZones = null;
            } else if (hrZones.isEmpty()) {
                this.hrZones = Optional.empty();
            } else {
                this.hrZones = Optional.of(hrZones.get());
            }
            return this;
        }

        /**
         * <p>Time in seconds spent in different heart rate zones &lt;50%, 50-60%, 60-70%, 70-80%, 80-90%, 90%+. Due to rounding errors, it's possible that summing all values is different than the total time of the workout. Not available for all providers::seconds</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage hrZones(List<Integer> hrZones) {
            this.hrZones = Optional.ofNullable(hrZones);
            return this;
        }

        /**
         * <p>Time in seconds spent in different heart rate zones &lt;50%, 50-60%, 60-70%, 70-80%, 80-90%, 90%+. Due to rounding errors, it's possible that summing all values is different than the total time of the workout. Not available for all providers::seconds</p>
         */
        @java.lang.Override
        @JsonSetter(value = "hr_zones", nulls = Nulls.SKIP)
        public _FinalStage hrZones(Optional<List<Integer>> hrZones) {
            this.hrZones = hrZones;
            return this;
        }

        /**
         * <p>Sport's name</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage sport(ClientFacingSport sport) {
            this.sport = Optional.ofNullable(sport);
            return this;
        }

        /**
         * <p>Sport's name</p>
         */
        @java.lang.Override
        @JsonSetter(value = "sport", nulls = Nulls.SKIP)
        public _FinalStage sport(Optional<ClientFacingSport> sport) {
            this.sport = sport;
            return this;
        }

        /**
         * <p>Calories burned during the workout::kCal</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage calories(Nullable<Double> calories) {
            if (calories.isNull()) {
                this.calories = null;
            } else if (calories.isEmpty()) {
                this.calories = Optional.empty();
            } else {
                this.calories = Optional.of(calories.get());
            }
            return this;
        }

        /**
         * <p>Calories burned during the workout::kCal</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage calories(Double calories) {
            this.calories = Optional.ofNullable(calories);
            return this;
        }

        /**
         * <p>Calories burned during the workout::kCal</p>
         */
        @java.lang.Override
        @JsonSetter(value = "calories", nulls = Nulls.SKIP)
        public _FinalStage calories(Optional<Double> calories) {
            this.calories = calories;
            return this;
        }

        /**
         * <p>Distance travelled during workout::meters</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage distance(Nullable<Double> distance) {
            if (distance.isNull()) {
                this.distance = null;
            } else if (distance.isEmpty()) {
                this.distance = Optional.empty();
            } else {
                this.distance = Optional.of(distance.get());
            }
            return this;
        }

        /**
         * <p>Distance travelled during workout::meters</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage distance(Double distance) {
            this.distance = Optional.ofNullable(distance);
            return this;
        }

        /**
         * <p>Distance travelled during workout::meters</p>
         */
        @java.lang.Override
        @JsonSetter(value = "distance", nulls = Nulls.SKIP)
        public _FinalStage distance(Optional<Double> distance) {
            this.distance = distance;
            return this;
        }

        /**
         * <p>Max heart rate during workout::bpm</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage maxHr(Nullable<Integer> maxHr) {
            if (maxHr.isNull()) {
                this.maxHr = null;
            } else if (maxHr.isEmpty()) {
                this.maxHr = Optional.empty();
            } else {
                this.maxHr = Optional.of(maxHr.get());
            }
            return this;
        }

        /**
         * <p>Max heart rate during workout::bpm</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage maxHr(Integer maxHr) {
            this.maxHr = Optional.ofNullable(maxHr);
            return this;
        }

        /**
         * <p>Max heart rate during workout::bpm</p>
         */
        @java.lang.Override
        @JsonSetter(value = "max_hr", nulls = Nulls.SKIP)
        public _FinalStage maxHr(Optional<Integer> maxHr) {
            this.maxHr = maxHr;
            return this;
        }

        /**
         * <p>Average heart rate during workout::bpm</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage averageHr(Nullable<Integer> averageHr) {
            if (averageHr.isNull()) {
                this.averageHr = null;
            } else if (averageHr.isEmpty()) {
                this.averageHr = Optional.empty();
            } else {
                this.averageHr = Optional.of(averageHr.get());
            }
            return this;
        }

        /**
         * <p>Average heart rate during workout::bpm</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage averageHr(Integer averageHr) {
            this.averageHr = Optional.ofNullable(averageHr);
            return this;
        }

        /**
         * <p>Average heart rate during workout::bpm</p>
         */
        @java.lang.Override
        @JsonSetter(value = "average_hr", nulls = Nulls.SKIP)
        public _FinalStage averageHr(Optional<Integer> averageHr) {
            this.averageHr = averageHr;
            return this;
        }

        /**
         * <p>Timezone offset from UTC as seconds. For example, EEST (Eastern European Summer Time, +3h) is 10800. PST (Pacific Standard Time, -8h) is -28800::seconds</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage timezoneOffset(Nullable<Integer> timezoneOffset) {
            if (timezoneOffset.isNull()) {
                this.timezoneOffset = null;
            } else if (timezoneOffset.isEmpty()) {
                this.timezoneOffset = Optional.empty();
            } else {
                this.timezoneOffset = Optional.of(timezoneOffset.get());
            }
            return this;
        }

        /**
         * <p>Timezone offset from UTC as seconds. For example, EEST (Eastern European Summer Time, +3h) is 10800. PST (Pacific Standard Time, -8h) is -28800::seconds</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage timezoneOffset(Integer timezoneOffset) {
            this.timezoneOffset = Optional.ofNullable(timezoneOffset);
            return this;
        }

        /**
         * <p>Timezone offset from UTC as seconds. For example, EEST (Eastern European Summer Time, +3h) is 10800. PST (Pacific Standard Time, -8h) is -28800::seconds</p>
         */
        @java.lang.Override
        @JsonSetter(value = "timezone_offset", nulls = Nulls.SKIP)
        public _FinalStage timezoneOffset(Optional<Integer> timezoneOffset) {
            this.timezoneOffset = timezoneOffset;
            return this;
        }

        /**
         * <p>Title given for the workout</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage title(Nullable<String> title) {
            if (title.isNull()) {
                this.title = null;
            } else if (title.isEmpty()) {
                this.title = Optional.empty();
            } else {
                this.title = Optional.of(title.get());
            }
            return this;
        }

        /**
         * <p>Title given for the workout</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage title(String title) {
            this.title = Optional.ofNullable(title);
            return this;
        }

        /**
         * <p>Title given for the workout</p>
         */
        @java.lang.Override
        @JsonSetter(value = "title", nulls = Nulls.SKIP)
        public _FinalStage title(Optional<String> title) {
            this.title = title;
            return this;
        }

        @java.lang.Override
        public ClientFacingWorkout build() {
            return new ClientFacingWorkout(
                    id,
                    userId,
                    title,
                    timezoneOffset,
                    averageHr,
                    maxHr,
                    distance,
                    calendarDate,
                    timeStart,
                    timeEnd,
                    calories,
                    sport,
                    hrZones,
                    movingTime,
                    totalElevationGain,
                    elevHigh,
                    elevLow,
                    averageSpeed,
                    maxSpeed,
                    averageWatts,
                    deviceWatts,
                    maxWatts,
                    weightedAverageWatts,
                    steps,
                    map,
                    providerId,
                    source,
                    createdAt,
                    updatedAt,
                    additionalProperties);
        }
    }
}
