/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vital.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.vital.api.core.Nullable;
import com.vital.api.core.NullableNonemptyFilter;
import com.vital.api.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = HistoricalPullTimeline.Builder.class)
public final class HistoricalPullTimeline {
    private final OffsetDateTime scheduledAt;

    private final Optional<OffsetDateTime> startedAt;

    private final Optional<OffsetDateTime> endedAt;

    private final Map<String, Object> additionalProperties;

    private HistoricalPullTimeline(
            OffsetDateTime scheduledAt,
            Optional<OffsetDateTime> startedAt,
            Optional<OffsetDateTime> endedAt,
            Map<String, Object> additionalProperties) {
        this.scheduledAt = scheduledAt;
        this.startedAt = startedAt;
        this.endedAt = endedAt;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("scheduled_at")
    public OffsetDateTime getScheduledAt() {
        return scheduledAt;
    }

    @JsonIgnore
    public Optional<OffsetDateTime> getStartedAt() {
        if (startedAt == null) {
            return Optional.empty();
        }
        return startedAt;
    }

    @JsonIgnore
    public Optional<OffsetDateTime> getEndedAt() {
        if (endedAt == null) {
            return Optional.empty();
        }
        return endedAt;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("started_at")
    private Optional<OffsetDateTime> _getStartedAt() {
        return startedAt;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("ended_at")
    private Optional<OffsetDateTime> _getEndedAt() {
        return endedAt;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof HistoricalPullTimeline && equalTo((HistoricalPullTimeline) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(HistoricalPullTimeline other) {
        return scheduledAt.equals(other.scheduledAt)
                && startedAt.equals(other.startedAt)
                && endedAt.equals(other.endedAt);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.scheduledAt, this.startedAt, this.endedAt);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ScheduledAtStage builder() {
        return new Builder();
    }

    public interface ScheduledAtStage {
        _FinalStage scheduledAt(@NotNull OffsetDateTime scheduledAt);

        Builder from(HistoricalPullTimeline other);
    }

    public interface _FinalStage {
        HistoricalPullTimeline build();

        _FinalStage startedAt(Optional<OffsetDateTime> startedAt);

        _FinalStage startedAt(OffsetDateTime startedAt);

        _FinalStage startedAt(Nullable<OffsetDateTime> startedAt);

        _FinalStage endedAt(Optional<OffsetDateTime> endedAt);

        _FinalStage endedAt(OffsetDateTime endedAt);

        _FinalStage endedAt(Nullable<OffsetDateTime> endedAt);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ScheduledAtStage, _FinalStage {
        private OffsetDateTime scheduledAt;

        private Optional<OffsetDateTime> endedAt = Optional.empty();

        private Optional<OffsetDateTime> startedAt = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(HistoricalPullTimeline other) {
            scheduledAt(other.getScheduledAt());
            startedAt(other.getStartedAt());
            endedAt(other.getEndedAt());
            return this;
        }

        @java.lang.Override
        @JsonSetter("scheduled_at")
        public _FinalStage scheduledAt(@NotNull OffsetDateTime scheduledAt) {
            this.scheduledAt = Objects.requireNonNull(scheduledAt, "scheduledAt must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage endedAt(Nullable<OffsetDateTime> endedAt) {
            if (endedAt.isNull()) {
                this.endedAt = null;
            } else if (endedAt.isEmpty()) {
                this.endedAt = Optional.empty();
            } else {
                this.endedAt = Optional.of(endedAt.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage endedAt(OffsetDateTime endedAt) {
            this.endedAt = Optional.ofNullable(endedAt);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "ended_at", nulls = Nulls.SKIP)
        public _FinalStage endedAt(Optional<OffsetDateTime> endedAt) {
            this.endedAt = endedAt;
            return this;
        }

        @java.lang.Override
        public _FinalStage startedAt(Nullable<OffsetDateTime> startedAt) {
            if (startedAt.isNull()) {
                this.startedAt = null;
            } else if (startedAt.isEmpty()) {
                this.startedAt = Optional.empty();
            } else {
                this.startedAt = Optional.of(startedAt.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage startedAt(OffsetDateTime startedAt) {
            this.startedAt = Optional.ofNullable(startedAt);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "started_at", nulls = Nulls.SKIP)
        public _FinalStage startedAt(Optional<OffsetDateTime> startedAt) {
            this.startedAt = startedAt;
            return this;
        }

        @java.lang.Override
        public HistoricalPullTimeline build() {
            return new HistoricalPullTimeline(scheduledAt, startedAt, endedAt, additionalProperties);
        }
    }
}
