/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vital.api.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum HomePregnancyTestEntryTestResult {
    NEGATIVE("negative"),

    POSITIVE("positive"),

    INDETERMINATE("indeterminate");

    private final String value;

    HomePregnancyTestEntryTestResult(String value) {
        this.value = value;
    }

    @JsonValue
    @Override
    public String toString() {
        return this.value;
    }
}
