/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vital.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.vital.api.core.Nullable;
import com.vital.api.core.NullableNonemptyFilter;
import com.vital.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = Micros.Builder.class)
public final class Micros {
    private final Optional<Map<String, Optional<Double>>> minerals;

    private final Optional<Map<String, Optional<Double>>> traceElements;

    private final Optional<Map<String, Optional<Double>>> vitamins;

    private final Map<String, Object> additionalProperties;

    private Micros(
            Optional<Map<String, Optional<Double>>> minerals,
            Optional<Map<String, Optional<Double>>> traceElements,
            Optional<Map<String, Optional<Double>>> vitamins,
            Map<String, Object> additionalProperties) {
        this.minerals = minerals;
        this.traceElements = traceElements;
        this.vitamins = vitamins;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Amount of each mineral in their respective units. Most minerals are measured in mg (milligrams), while sodium and potassium are in g (grams).
     */
    @JsonIgnore
    public Optional<Map<String, Optional<Double>>> getMinerals() {
        if (minerals == null) {
            return Optional.empty();
        }
        return minerals;
    }

    /**
     * @return Amount of each trace element in their respective units, most measured in μg (micrograms), while copper and manganese are in mg (milligrams).
     */
    @JsonIgnore
    public Optional<Map<String, Optional<Double>>> getTraceElements() {
        if (traceElements == null) {
            return Optional.empty();
        }
        return traceElements;
    }

    /**
     * @return Amount of each vitamin in their respective units. A, B12, D and K in μg (micrograms), while B1, B2, B3, B5, B6, C and folic acid are in mg (milligrams).
     */
    @JsonIgnore
    public Optional<Map<String, Optional<Double>>> getVitamins() {
        if (vitamins == null) {
            return Optional.empty();
        }
        return vitamins;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("minerals")
    private Optional<Map<String, Optional<Double>>> _getMinerals() {
        return minerals;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("trace_elements")
    private Optional<Map<String, Optional<Double>>> _getTraceElements() {
        return traceElements;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("vitamins")
    private Optional<Map<String, Optional<Double>>> _getVitamins() {
        return vitamins;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof Micros && equalTo((Micros) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(Micros other) {
        return minerals.equals(other.minerals)
                && traceElements.equals(other.traceElements)
                && vitamins.equals(other.vitamins);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.minerals, this.traceElements, this.vitamins);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Map<String, Optional<Double>>> minerals = Optional.empty();

        private Optional<Map<String, Optional<Double>>> traceElements = Optional.empty();

        private Optional<Map<String, Optional<Double>>> vitamins = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(Micros other) {
            minerals(other.getMinerals());
            traceElements(other.getTraceElements());
            vitamins(other.getVitamins());
            return this;
        }

        /**
         * <p>Amount of each mineral in their respective units. Most minerals are measured in mg (milligrams), while sodium and potassium are in g (grams).</p>
         */
        @JsonSetter(value = "minerals", nulls = Nulls.SKIP)
        public Builder minerals(Optional<Map<String, Optional<Double>>> minerals) {
            this.minerals = minerals;
            return this;
        }

        public Builder minerals(Map<String, Optional<Double>> minerals) {
            this.minerals = Optional.ofNullable(minerals);
            return this;
        }

        public Builder minerals(Nullable<Map<String, Optional<Double>>> minerals) {
            if (minerals.isNull()) {
                this.minerals = null;
            } else if (minerals.isEmpty()) {
                this.minerals = Optional.empty();
            } else {
                this.minerals = Optional.of(minerals.get());
            }
            return this;
        }

        /**
         * <p>Amount of each trace element in their respective units, most measured in μg (micrograms), while copper and manganese are in mg (milligrams).</p>
         */
        @JsonSetter(value = "trace_elements", nulls = Nulls.SKIP)
        public Builder traceElements(Optional<Map<String, Optional<Double>>> traceElements) {
            this.traceElements = traceElements;
            return this;
        }

        public Builder traceElements(Map<String, Optional<Double>> traceElements) {
            this.traceElements = Optional.ofNullable(traceElements);
            return this;
        }

        public Builder traceElements(Nullable<Map<String, Optional<Double>>> traceElements) {
            if (traceElements.isNull()) {
                this.traceElements = null;
            } else if (traceElements.isEmpty()) {
                this.traceElements = Optional.empty();
            } else {
                this.traceElements = Optional.of(traceElements.get());
            }
            return this;
        }

        /**
         * <p>Amount of each vitamin in their respective units. A, B12, D and K in μg (micrograms), while B1, B2, B3, B5, B6, C and folic acid are in mg (milligrams).</p>
         */
        @JsonSetter(value = "vitamins", nulls = Nulls.SKIP)
        public Builder vitamins(Optional<Map<String, Optional<Double>>> vitamins) {
            this.vitamins = vitamins;
            return this;
        }

        public Builder vitamins(Map<String, Optional<Double>> vitamins) {
            this.vitamins = Optional.ofNullable(vitamins);
            return this;
        }

        public Builder vitamins(Nullable<Map<String, Optional<Double>>> vitamins) {
            if (vitamins.isNull()) {
                this.vitamins = null;
            } else if (vitamins.isEmpty()) {
                this.vitamins = Optional.empty();
            } else {
                this.vitamins = Optional.of(vitamins.get());
            }
            return this;
        }

        public Micros build() {
            return new Micros(minerals, traceElements, vitamins, additionalProperties);
        }
    }
}
