/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vital.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.vital.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ParsingJob.Builder.class)
public final class ParsingJob {
    private final String jobId;

    private final ParsingJobStatus status;

    private final Optional<ParsedLabReportData> data;

    private final boolean needsHumanReview;

    private final boolean isReviewed;

    private final Map<String, Object> additionalProperties;

    private ParsingJob(
            String jobId,
            ParsingJobStatus status,
            Optional<ParsedLabReportData> data,
            boolean needsHumanReview,
            boolean isReviewed,
            Map<String, Object> additionalProperties) {
        this.jobId = jobId;
        this.status = status;
        this.data = data;
        this.needsHumanReview = needsHumanReview;
        this.isReviewed = isReviewed;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("job_id")
    public String getJobId() {
        return jobId;
    }

    @JsonProperty("status")
    public ParsingJobStatus getStatus() {
        return status;
    }

    @JsonProperty("data")
    public Optional<ParsedLabReportData> getData() {
        return data;
    }

    @JsonProperty("needs_human_review")
    public boolean getNeedsHumanReview() {
        return needsHumanReview;
    }

    @JsonProperty("is_reviewed")
    public boolean getIsReviewed() {
        return isReviewed;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ParsingJob && equalTo((ParsingJob) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ParsingJob other) {
        return jobId.equals(other.jobId)
                && status.equals(other.status)
                && data.equals(other.data)
                && needsHumanReview == other.needsHumanReview
                && isReviewed == other.isReviewed;
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.jobId, this.status, this.data, this.needsHumanReview, this.isReviewed);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static JobIdStage builder() {
        return new Builder();
    }

    public interface JobIdStage {
        StatusStage jobId(@NotNull String jobId);

        Builder from(ParsingJob other);
    }

    public interface StatusStage {
        NeedsHumanReviewStage status(@NotNull ParsingJobStatus status);
    }

    public interface NeedsHumanReviewStage {
        IsReviewedStage needsHumanReview(boolean needsHumanReview);
    }

    public interface IsReviewedStage {
        _FinalStage isReviewed(boolean isReviewed);
    }

    public interface _FinalStage {
        ParsingJob build();

        _FinalStage data(Optional<ParsedLabReportData> data);

        _FinalStage data(ParsedLabReportData data);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements JobIdStage, StatusStage, NeedsHumanReviewStage, IsReviewedStage, _FinalStage {
        private String jobId;

        private ParsingJobStatus status;

        private boolean needsHumanReview;

        private boolean isReviewed;

        private Optional<ParsedLabReportData> data = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ParsingJob other) {
            jobId(other.getJobId());
            status(other.getStatus());
            data(other.getData());
            needsHumanReview(other.getNeedsHumanReview());
            isReviewed(other.getIsReviewed());
            return this;
        }

        @java.lang.Override
        @JsonSetter("job_id")
        public StatusStage jobId(@NotNull String jobId) {
            this.jobId = Objects.requireNonNull(jobId, "jobId must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("status")
        public NeedsHumanReviewStage status(@NotNull ParsingJobStatus status) {
            this.status = Objects.requireNonNull(status, "status must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("needs_human_review")
        public IsReviewedStage needsHumanReview(boolean needsHumanReview) {
            this.needsHumanReview = needsHumanReview;
            return this;
        }

        @java.lang.Override
        @JsonSetter("is_reviewed")
        public _FinalStage isReviewed(boolean isReviewed) {
            this.isReviewed = isReviewed;
            return this;
        }

        @java.lang.Override
        public _FinalStage data(ParsedLabReportData data) {
            this.data = Optional.ofNullable(data);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "data", nulls = Nulls.SKIP)
        public _FinalStage data(Optional<ParsedLabReportData> data) {
            this.data = data;
            return this;
        }

        @java.lang.Override
        public ParsingJob build() {
            return new ParsingJob(jobId, status, data, needsHumanReview, isReviewed, additionalProperties);
        }
    }
}
