/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vital.api.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum Priority {
    ROUTINE("routine"),

    URGENT("urgent"),

    ASAP("asap"),

    STAT("stat");

    private final String value;

    Priority(String value) {
        this.value = value;
    }

    @JsonValue
    @Override
    public String toString() {
        return this.value;
    }
}
