/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vital.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.vital.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonDeserialize(builder = PscAreaInfoDetails.Builder.class)
public final class PscAreaInfoDetails {
    private final int withinRadius;

    private final int radius;

    private final Map<String, Object> additionalProperties;

    private PscAreaInfoDetails(int withinRadius, int radius, Map<String, Object> additionalProperties) {
        this.withinRadius = withinRadius;
        this.radius = radius;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("within_radius")
    public int getWithinRadius() {
        return withinRadius;
    }

    @JsonProperty("radius")
    public int getRadius() {
        return radius;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof PscAreaInfoDetails && equalTo((PscAreaInfoDetails) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(PscAreaInfoDetails other) {
        return withinRadius == other.withinRadius && radius == other.radius;
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.withinRadius, this.radius);
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static WithinRadiusStage builder() {
        return new Builder();
    }

    public interface WithinRadiusStage {
        RadiusStage withinRadius(int withinRadius);

        Builder from(PscAreaInfoDetails other);
    }

    public interface RadiusStage {
        _FinalStage radius(int radius);
    }

    public interface _FinalStage {
        PscAreaInfoDetails build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements WithinRadiusStage, RadiusStage, _FinalStage {
        private int withinRadius;

        private int radius;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @Override
        public Builder from(PscAreaInfoDetails other) {
            withinRadius(other.getWithinRadius());
            radius(other.getRadius());
            return this;
        }

        @Override
        @JsonSetter("within_radius")
        public RadiusStage withinRadius(int withinRadius) {
            this.withinRadius = withinRadius;
            return this;
        }

        @Override
        @JsonSetter("radius")
        public _FinalStage radius(int radius) {
            this.radius = radius;
            return this;
        }

        @Override
        public PscAreaInfoDetails build() {
            return new PscAreaInfoDetails(withinRadius, radius, additionalProperties);
        }
    }
}
