/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vital.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.vital.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonDeserialize(builder = QueryConfig.Builder.class)
public final class QueryConfig {
    private final Optional<QueryConfigWeekStartsOn> weekStartsOn;

    private final Optional<List<QueryConfigProviderPriorityOverridesItem>> providerPriorityOverrides;

    private final Map<String, Object> additionalProperties;

    private QueryConfig(
            Optional<QueryConfigWeekStartsOn> weekStartsOn,
            Optional<List<QueryConfigProviderPriorityOverridesItem>> providerPriorityOverrides,
            Map<String, Object> additionalProperties) {
        this.weekStartsOn = weekStartsOn;
        this.providerPriorityOverrides = providerPriorityOverrides;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("week_starts_on")
    public Optional<QueryConfigWeekStartsOn> getWeekStartsOn() {
        return weekStartsOn;
    }

    @JsonProperty("provider_priority_overrides")
    public Optional<List<QueryConfigProviderPriorityOverridesItem>> getProviderPriorityOverrides() {
        return providerPriorityOverrides;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof QueryConfig && equalTo((QueryConfig) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(QueryConfig other) {
        return weekStartsOn.equals(other.weekStartsOn)
                && providerPriorityOverrides.equals(other.providerPriorityOverrides);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.weekStartsOn, this.providerPriorityOverrides);
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<QueryConfigWeekStartsOn> weekStartsOn = Optional.empty();

        private Optional<List<QueryConfigProviderPriorityOverridesItem>> providerPriorityOverrides = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(QueryConfig other) {
            weekStartsOn(other.getWeekStartsOn());
            providerPriorityOverrides(other.getProviderPriorityOverrides());
            return this;
        }

        @JsonSetter(value = "week_starts_on", nulls = Nulls.SKIP)
        public Builder weekStartsOn(Optional<QueryConfigWeekStartsOn> weekStartsOn) {
            this.weekStartsOn = weekStartsOn;
            return this;
        }

        public Builder weekStartsOn(QueryConfigWeekStartsOn weekStartsOn) {
            this.weekStartsOn = Optional.of(weekStartsOn);
            return this;
        }

        @JsonSetter(value = "provider_priority_overrides", nulls = Nulls.SKIP)
        public Builder providerPriorityOverrides(
                Optional<List<QueryConfigProviderPriorityOverridesItem>> providerPriorityOverrides) {
            this.providerPriorityOverrides = providerPriorityOverrides;
            return this;
        }

        public Builder providerPriorityOverrides(
                List<QueryConfigProviderPriorityOverridesItem> providerPriorityOverrides) {
            this.providerPriorityOverrides = Optional.of(providerPriorityOverrides);
            return this;
        }

        public QueryConfig build() {
            return new QueryConfig(weekStartsOn, providerPriorityOverrides, additionalProperties);
        }
    }
}
