/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vital.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.vital.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonDeserialize(builder = ResourceAvailability.Builder.class)
public final class ResourceAvailability {
    private final Availability status;

    private final Optional<ScopeRequirementsGrants> scopeRequirements;

    private final Map<String, Object> additionalProperties;

    private ResourceAvailability(
            Availability status,
            Optional<ScopeRequirementsGrants> scopeRequirements,
            Map<String, Object> additionalProperties) {
        this.status = status;
        this.scopeRequirements = scopeRequirements;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("status")
    public Availability getStatus() {
        return status;
    }

    @JsonProperty("scope_requirements")
    public Optional<ScopeRequirementsGrants> getScopeRequirements() {
        return scopeRequirements;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ResourceAvailability && equalTo((ResourceAvailability) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ResourceAvailability other) {
        return status.equals(other.status) && scopeRequirements.equals(other.scopeRequirements);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.status, this.scopeRequirements);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static StatusStage builder() {
        return new Builder();
    }

    public interface StatusStage {
        _FinalStage status(Availability status);

        Builder from(ResourceAvailability other);
    }

    public interface _FinalStage {
        ResourceAvailability build();

        _FinalStage scopeRequirements(Optional<ScopeRequirementsGrants> scopeRequirements);

        _FinalStage scopeRequirements(ScopeRequirementsGrants scopeRequirements);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements StatusStage, _FinalStage {
        private Availability status;

        private Optional<ScopeRequirementsGrants> scopeRequirements = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ResourceAvailability other) {
            status(other.getStatus());
            scopeRequirements(other.getScopeRequirements());
            return this;
        }

        @java.lang.Override
        @JsonSetter("status")
        public _FinalStage status(Availability status) {
            this.status = status;
            return this;
        }

        @java.lang.Override
        public _FinalStage scopeRequirements(ScopeRequirementsGrants scopeRequirements) {
            this.scopeRequirements = Optional.of(scopeRequirements);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "scope_requirements", nulls = Nulls.SKIP)
        public _FinalStage scopeRequirements(Optional<ScopeRequirementsGrants> scopeRequirements) {
            this.scopeRequirements = scopeRequirements;
            return this;
        }

        @java.lang.Override
        public ResourceAvailability build() {
            return new ResourceAvailability(status, scopeRequirements, additionalProperties);
        }
    }
}
