/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vital.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.vital.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonDeserialize(builder = TemperatureTimeseriesExpr.Builder.class)
public final class TemperatureTimeseriesExpr {
    private final TemperatureTimeseriesExprTimeseries timeseries;

    private final TemperatureTimeseriesExprField field;

    private final Map<String, Object> additionalProperties;

    private TemperatureTimeseriesExpr(
            TemperatureTimeseriesExprTimeseries timeseries,
            TemperatureTimeseriesExprField field,
            Map<String, Object> additionalProperties) {
        this.timeseries = timeseries;
        this.field = field;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return ℹ️ This enum is non-exhaustive.
     */
    @JsonProperty("timeseries")
    public TemperatureTimeseriesExprTimeseries getTimeseries() {
        return timeseries;
    }

    /**
     * @return ℹ️ This enum is non-exhaustive.
     */
    @JsonProperty("field")
    public TemperatureTimeseriesExprField getField() {
        return field;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof TemperatureTimeseriesExpr && equalTo((TemperatureTimeseriesExpr) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(TemperatureTimeseriesExpr other) {
        return timeseries.equals(other.timeseries) && field.equals(other.field);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.timeseries, this.field);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static TimeseriesStage builder() {
        return new Builder();
    }

    public interface TimeseriesStage {
        FieldStage timeseries(TemperatureTimeseriesExprTimeseries timeseries);

        Builder from(TemperatureTimeseriesExpr other);
    }

    public interface FieldStage {
        _FinalStage field(TemperatureTimeseriesExprField field);
    }

    public interface _FinalStage {
        TemperatureTimeseriesExpr build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements TimeseriesStage, FieldStage, _FinalStage {
        private TemperatureTimeseriesExprTimeseries timeseries;

        private TemperatureTimeseriesExprField field;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(TemperatureTimeseriesExpr other) {
            timeseries(other.getTimeseries());
            field(other.getField());
            return this;
        }

        /**
         * <p>ℹ️ This enum is non-exhaustive.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("timeseries")
        public FieldStage timeseries(TemperatureTimeseriesExprTimeseries timeseries) {
            this.timeseries = timeseries;
            return this;
        }

        /**
         * <p>ℹ️ This enum is non-exhaustive.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("field")
        public _FinalStage field(TemperatureTimeseriesExprField field) {
            this.field = field;
            return this;
        }

        @java.lang.Override
        public TemperatureTimeseriesExpr build() {
            return new TemperatureTimeseriesExpr(timeseries, field, additionalProperties);
        }
    }
}
