/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vital.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.vital.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = UserSignInTokenResponse.Builder.class)
public final class UserSignInTokenResponse {
    private final String userId;

    private final String signInToken;

    private final Map<String, Object> additionalProperties;

    private UserSignInTokenResponse(String userId, String signInToken, Map<String, Object> additionalProperties) {
        this.userId = userId;
        this.signInToken = signInToken;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("user_id")
    public String getUserId() {
        return userId;
    }

    @JsonProperty("sign_in_token")
    public String getSignInToken() {
        return signInToken;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof UserSignInTokenResponse && equalTo((UserSignInTokenResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(UserSignInTokenResponse other) {
        return userId.equals(other.userId) && signInToken.equals(other.signInToken);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.userId, this.signInToken);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static UserIdStage builder() {
        return new Builder();
    }

    public interface UserIdStage {
        SignInTokenStage userId(@NotNull String userId);

        Builder from(UserSignInTokenResponse other);
    }

    public interface SignInTokenStage {
        _FinalStage signInToken(@NotNull String signInToken);
    }

    public interface _FinalStage {
        UserSignInTokenResponse build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements UserIdStage, SignInTokenStage, _FinalStage {
        private String userId;

        private String signInToken;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(UserSignInTokenResponse other) {
            userId(other.getUserId());
            signInToken(other.getSignInToken());
            return this;
        }

        @java.lang.Override
        @JsonSetter("user_id")
        public SignInTokenStage userId(@NotNull String userId) {
            this.userId = Objects.requireNonNull(userId, "userId must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("sign_in_token")
        public _FinalStage signInToken(@NotNull String signInToken) {
            this.signInToken = Objects.requireNonNull(signInToken, "signInToken must not be null");
            return this;
        }

        @java.lang.Override
        public UserSignInTokenResponse build() {
            return new UserSignInTokenResponse(userId, signInToken, additionalProperties);
        }
    }
}
