/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vital.api.resources.link.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.vital.api.core.Nullable;
import com.vital.api.core.NullableNonemptyFilter;
import com.vital.api.core.ObjectMappers;
import com.vital.api.types.Providers;
import com.vital.api.types.Region;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = EmailProviderAuthLink.Builder.class)
public final class EmailProviderAuthLink {
    private final Optional<String> vitalLinkToken;

    private final String email;

    private final Optional<Providers> emailProviderAuthLinkProvider;

    private final Optional<Region> region;

    private final Map<String, Object> additionalProperties;

    private EmailProviderAuthLink(
            Optional<String> vitalLinkToken,
            String email,
            Optional<Providers> emailProviderAuthLinkProvider,
            Optional<Region> region,
            Map<String, Object> additionalProperties) {
        this.vitalLinkToken = vitalLinkToken;
        this.email = email;
        this.emailProviderAuthLinkProvider = emailProviderAuthLinkProvider;
        this.region = region;
        this.additionalProperties = additionalProperties;
    }

    @JsonIgnore
    public Optional<String> getVitalLinkToken() {
        if (vitalLinkToken == null) {
            return Optional.empty();
        }
        return vitalLinkToken;
    }

    @JsonProperty("email")
    public String getEmail() {
        return email;
    }

    @JsonIgnore
    public Optional<Providers> getEmailProviderAuthLinkProvider() {
        if (emailProviderAuthLinkProvider == null) {
            return Optional.empty();
        }
        return emailProviderAuthLinkProvider;
    }

    @JsonProperty("region")
    public Optional<Region> getRegion() {
        return region;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("x-vital-link-token")
    private Optional<String> _getVitalLinkToken() {
        return vitalLinkToken;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("provider")
    private Optional<Providers> _getEmailProviderAuthLinkProvider() {
        return emailProviderAuthLinkProvider;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof EmailProviderAuthLink && equalTo((EmailProviderAuthLink) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(EmailProviderAuthLink other) {
        return vitalLinkToken.equals(other.vitalLinkToken)
                && email.equals(other.email)
                && emailProviderAuthLinkProvider.equals(other.emailProviderAuthLinkProvider)
                && region.equals(other.region);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.vitalLinkToken, this.email, this.emailProviderAuthLinkProvider, this.region);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static EmailStage builder() {
        return new Builder();
    }

    public interface EmailStage {
        _FinalStage email(@NotNull String email);

        Builder from(EmailProviderAuthLink other);
    }

    public interface _FinalStage {
        EmailProviderAuthLink build();

        _FinalStage vitalLinkToken(Optional<String> vitalLinkToken);

        _FinalStage vitalLinkToken(String vitalLinkToken);

        _FinalStage vitalLinkToken(Nullable<String> vitalLinkToken);

        _FinalStage emailProviderAuthLinkProvider(Optional<Providers> emailProviderAuthLinkProvider);

        _FinalStage emailProviderAuthLinkProvider(Providers emailProviderAuthLinkProvider);

        _FinalStage emailProviderAuthLinkProvider(Nullable<Providers> emailProviderAuthLinkProvider);

        _FinalStage region(Optional<Region> region);

        _FinalStage region(Region region);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements EmailStage, _FinalStage {
        private String email;

        private Optional<Region> region = Optional.empty();

        private Optional<Providers> emailProviderAuthLinkProvider = Optional.empty();

        private Optional<String> vitalLinkToken = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(EmailProviderAuthLink other) {
            vitalLinkToken(other.getVitalLinkToken());
            email(other.getEmail());
            emailProviderAuthLinkProvider(other.getEmailProviderAuthLinkProvider());
            region(other.getRegion());
            return this;
        }

        @java.lang.Override
        @JsonSetter("email")
        public _FinalStage email(@NotNull String email) {
            this.email = Objects.requireNonNull(email, "email must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage region(Region region) {
            this.region = Optional.ofNullable(region);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "region", nulls = Nulls.SKIP)
        public _FinalStage region(Optional<Region> region) {
            this.region = region;
            return this;
        }

        @java.lang.Override
        public _FinalStage emailProviderAuthLinkProvider(Nullable<Providers> emailProviderAuthLinkProvider) {
            if (emailProviderAuthLinkProvider.isNull()) {
                this.emailProviderAuthLinkProvider = null;
            } else if (emailProviderAuthLinkProvider.isEmpty()) {
                this.emailProviderAuthLinkProvider = Optional.empty();
            } else {
                this.emailProviderAuthLinkProvider = Optional.of(emailProviderAuthLinkProvider.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage emailProviderAuthLinkProvider(Providers emailProviderAuthLinkProvider) {
            this.emailProviderAuthLinkProvider = Optional.ofNullable(emailProviderAuthLinkProvider);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "provider", nulls = Nulls.SKIP)
        public _FinalStage emailProviderAuthLinkProvider(Optional<Providers> emailProviderAuthLinkProvider) {
            this.emailProviderAuthLinkProvider = emailProviderAuthLinkProvider;
            return this;
        }

        @java.lang.Override
        public _FinalStage vitalLinkToken(Nullable<String> vitalLinkToken) {
            if (vitalLinkToken.isNull()) {
                this.vitalLinkToken = null;
            } else if (vitalLinkToken.isEmpty()) {
                this.vitalLinkToken = Optional.empty();
            } else {
                this.vitalLinkToken = Optional.of(vitalLinkToken.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage vitalLinkToken(String vitalLinkToken) {
            this.vitalLinkToken = Optional.ofNullable(vitalLinkToken);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "x-vital-link-token", nulls = Nulls.SKIP)
        public _FinalStage vitalLinkToken(Optional<String> vitalLinkToken) {
            this.vitalLinkToken = vitalLinkToken;
            return this;
        }

        @java.lang.Override
        public EmailProviderAuthLink build() {
            return new EmailProviderAuthLink(
                    vitalLinkToken, email, emailProviderAuthLinkProvider, region, additionalProperties);
        }
    }
}
